kind: Secret
apiVersion: v1
metadata:
  name: git-auth-secret
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://misoboy:<Github Token>@https://github.com
---
